### ISSUE TITLE
why don't you use mcp over xds?

### ISSUE THREAD

**Issue by htn4179** [aeraki-framework/aeraki#56]
as we all know, istio 1.9 removed some mcp support

**Comment by zhaohuabing** [comment]
We have decided to directly create EnvoyFilters in K8s config store https://github.com/aeraki-framework/aeraki/pull/54 . This approach is preferred over mcp over xds because the generated EnvoyFilters are visible through Kubectl command tool, which is more convenient for users to figure out what changes has Aeraki done to the mesh.
